# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.25.225714'

RELEASE_GIT_HEAD = '4d076a04a8b353187056e637dd8eb4a384c319ab'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'SoSJames/yt-dlp'

ORIGIN = 'SoSJames/yt-dlp'

_pkg_version = '2024.04.25.225714'
